name: Bug Report
description: Reporte um problema para ajudarmos a corrigir
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Resumo
      description: O que está acontecendo?
      placeholder: Descreva o bug de forma objetiva.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Como reproduzir o problema?
      placeholder: |
        1. Vá em...
        2. Clique em...
        3. Veja...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Resultado esperado
      placeholder: O que deveria acontecer?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Resultado atual
      placeholder: O que acontece de fato?
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Ambiente
      description: Onde ocorreu? (dev/hml/prod + versão)
      placeholder: "prod | v1.2.3"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Evidências
      description: Cole logs relevantes (remova segredos!)
      render: shell
    validations:
      required: false
