name: Feature Request
description: Sugira uma melhoria/feature
title: "[FEAT] "
labels: ["enhancement"]
assignees: []
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema / contexto
      description: Qual problema isso resolve?
      placeholder: Hoje acontece..., precisamos...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposta
      description: O que você sugere?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Critérios de aceite
      placeholder: |
        - [ ] Deve...
        - [ ] Não deve...
    validations:
      required: false
